### ISSUE TITLE
Erro

### ISSUE THREAD

**Issue by ubedabtos** [victor-torres/sinesp-client#49]
Victor, minha aplicação python está apresentando esse erro. Sabe me dizer como solucionar??

Traceback (most recent call last):
  File "C:\Users\Ubeda\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "C:\Users\Ubeda\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\util\connection.py", line 80, in create_connection
    raise err
  File "C:\Users\Ubeda\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\util\connection.py", line 70, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] Uma tentativa de conexão falhou porque o componente conectado não respondeu
corretamente após um período de tempo ou a conexão estabelecida falhou
porque o host conectado não respondeu

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Ubeda\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Users\Ubeda\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "C:\Users\Ubeda\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "C:\Users\Ubeda\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connection.py", line 301, in connect
    conn = self._new_conn()
  File "C:\Users\Ubeda\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x000001F6391E2BE0>: Failed to establish a new connection: [WinError 10060] Uma tentativa de conexão falhou porque o componente conectado não respondeu
corretamente após um período de tempo ou a conexão estabelecida falhou
porque o host conectado não respondeu

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Ubeda\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Users\Ubeda\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\Ubeda\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\util\retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='sinespcidadao.sinesp.gov.br', port=443): Max retries exceeded with url: /sinesp-cidadao/captchaMobile.png (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001F6391E2BE0>: Failed to establish a new connection: [WinError 10060] Uma tentativa de conexão falhou porque o componente conectado não respondeu\r\ncorretamente após um período de tempo ou a conexão estabelecida falhou\r\nporque o host conectado não respondeu',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Ubeda\Desktop\Projeto Sentinela\openalpr\layout.py", line 131, in <module>
    sinesp("AAA1234")
  File "c:\Users\Ubeda\Desktop\Projeto Sentinela\openalpr\layout.py", line 89, in sinesp
    result = sc.search(placa)
  File "C:\Users\Ubeda\AppData\Local\Programs\Python\Python36\lib\site-packages\sinesp_client\__init__.py", line 176, in search
    response = self._request(plate).content
  File "C:\Users\Ubeda\AppData\Local\Programs\Python\Python36\lib\site-packages\sinesp_client\__init__.py", line 105, in _request
    cookies = self._captcha_cookie()
  File "C:\Users\Ubeda\AppData\Local\Programs\Python\Python36\lib\site-packages\sinesp_client\__init__.py", line 95, in _captcha_cookie
    cookies = requests.get('https://sinespcidadao.sinesp.gov.br/sinesp-cidadao/captchaMobile.png', proxies=self._proxies, verify=False).cookies
  File "C:\Users\Ubeda\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\Ubeda\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Ubeda\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Ubeda\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Ubeda\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='sinespcidadao.sinesp.gov.br', port=443): Max retries exceeded with url: /sinesp-cidadao/captchaMobile.png (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001F6391E2BE0>: Failed to establish a new connection: [WinError 10060] Uma tentativa de conexão falhou porque o componente conectado não respondeu\r\ncorretamente após um período de tempo ou 
a conexão estabelecida falhou\r\nporque o host conectado não respondeu',))

**Comment by victor-torres** [comment]
Olá, @ubedabtos. Veja nas issues anteriores que o suporte a essa lib foi descontinuado. 

Provavelmente o seu endereço IP foi bloqueado ou eles descontinuaram esse endpoint da API.
